### ISSUE TITLE
Error message when editing .tl file

### ISSUE THREAD

**Issue by Grinshpon** [teal-language/vscode-teal#30] opened 2021-02-08 22:04 UTC
First of all, I'm not actually using vscode, I'm using an editor called Onivim2, which is in currently in development (I'm using a beta) but it supports vscode extensions. So this may be the result of my setup, but I'm not sure yet. I've already shared this with the Oni2 community to figure out what's going on.

I have tl v0.11.1 and this is on Windows 10.

When I try to edit a tl file, [a bunch of these messages will pop up](https://i.imgur.com/czNcXia.png):

`'undefined' is not recognized as an internal or external command, operable program, or batch file.`

**Comment by pdesaulniers** [comment] 2021-02-08 22:46
Thanks for the bug report! I don't have a Windows machine readily available right now, but I suppose the `Teal > Compiler path` setting is not being read correctly... 

I just got rid of this setting and pushed a new release (0.6.3). Does it work now?

**Comment by Grinshpon** [comment] 2021-02-08 22:59
I'm getting a different error now:

```
[Error]

C:\Program Files (x86)\WinLua\Lua\5.3\bin\lua.exe: ...aming\luarocks\lib\luarocks\rocks-5.3\tl\0.11.1-1\bin\tl:864: assertion failed!
stack traceback:
        [C]: in function 'assert'
        ...aming\luarocks\lib\luarocks\rocks-5.3\tl\0.11.1-1\bin\tl:864: in upvalue 'json_out'
        ...aming\luarocks\lib\luarocks\rocks-5.3\tl\0.11.1-1\bin\tl:882: in upvalue 'json_out'
        ...aming\luarocks\lib\luarocks\rocks-5.3\tl\0.11.1-1\bin\tl:882: in upvalue 'json_out'
        ...aming\luarocks\lib\luarocks\rocks-5.3\tl\0.11.1-1\bin\tl:882: in local 'json_out'
        ...aming\luarocks\lib\luarocks\rocks-5.3\tl\0.11.1-1\bin\tl:926: in main chunk
        [C]: in ?
```

**Comment by pdesaulniers** [comment] 2021-02-08 23:07
OK, looks like the compiler is crashing. Can you reproduce this bug by running `tl types <filename>` on the file that is causing the error?

**Comment by Grinshpon** [comment] 2021-02-08 23:31
> 
> 
> OK, looks like the compiler is crashing. Can you reproduce this bug by running `tl types <filename>` on the file that is causing the error? (on the command line)

Yes, the same assertion fails when I run `tl types`. This isn't a specific file though, it's happening with every .tl file in the project. So I made a new directory and made a simple tl file, and `tl types` worked, and there were no error messages in the editor. So this leads me to believe that there is some problem with either the compiler or my `tlconfig.lua`, which I'll share below just in case:

```lua
return {
  skip_compat53 = true,
  preload_modules = {
    "love",
  },
  source_dir = "src",
  include_dir = {
    "src",
    --"assets",
  },
  include = {"*.tl", "*.d.tl"},
  build_dir = "app",
}
```

**Comment by Grinshpon** [comment] 2021-02-08 23:34
I feel I should also mention that I can build the project just fine, and the generated lua files run fine as well.

**Comment by pdesaulniers** [comment] 2021-02-09 00:02
Thanks for the details! I'd say it's a bug in the compiler.

Can you figure out a minimal reproduction and report the issue in https://github.com/teal-language/tl ?

**Comment by Grinshpon** [comment] 2021-02-09 00:19
I've narrowed it down to the `love.d.tl` file. I'll report the issue, thanks for the help!

**Comment by pdesaulniers** [comment] 2021-02-09 01:11
Sweet! I'm closing this issue for now.

**Closed by pdesaulniers** 2021-02-09 01:11 UTC
Labels: bug
